script: "bundle exec rake spec"

rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head

gemfile:
  - gemfiles/active_record_32.gemfile
  - gemfiles/data_mapper_12.gemfile
  - gemfiles/mongo_mapper.gemfile
  - gemfiles/mongoid_24.gemfile
  - gemfiles/sinatra.gemfile
